language: c

# Let's build everything for now; comment this out
#branches:
#  only:
#    - master 

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - octave
      - octave-pkg-dev
      - qttools5-dev-tools
      - libqt5sql5-sqlite
  homebrew:
    packages:
      - octave
      - qt
      - findutils

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1

script:
  - which octave
  - octave --version
  - make local
  # We only build the docs on Linux because it requires TeX and the macOS TeX install is a monster
  # We only need the doc build for verifying doc changes anyway; we don't need multi-platform
  # artifacts, or even the new artifacts at all.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make maintainer-clean && make all); fi
  - make test
  - make dist

