language: c

# Let's build everything for now; comment this out
#branches:
#  only:
#    - master

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - qttools5-dev-tools
      - libqt5sql5-sqlite
      - libjsoncpp-dev
  homebrew:
    packages:
      - octave
      - qt
      - findutils
      - jsoncpp

matrix:
  include:
    - os: linux
      dist: xenial
      env: dist="Xenial"
    - os: linux
      dist: trusty
      env: dist="Trusty"
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10

install:
  # Install Octave 4.2, even if it's not the default
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dev-tools/install-octave-4.2-ubuntu.sh; fi
  - which octave
  - octave --version

script:
  - make local
  # We only build the docs on Linux because it requires TeX and the macOS TeX install is a monster.
  # We only need the doc build for verifying doc changes anyway; we don't need multi-platform
  # artifacts, or even the new artifacts at all.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make maintainer-clean && make all); fi
  - make test
  - make dist
  - octave --no-gui --eval "pkg install ./target/jsonstuff-0.1.0.tar.gz"
  - octave --no-gui --eval "pkg load jsonstuff; pkg unload jsonstuff"
  - octave --no-gui --eval "pkg load jsonstuff; runtests ./inst"
  - octave --no-gui --eval "pkg uninstall jsonstuff"
