language: c

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

env:
  global:
    - OCTAVE_VER=4.4
    - OCTAVE=octave
    - OCT_PKG=jsonstuff
    - OCT_PKG_VER=0.3.4-SNAPSHOT

addons:
  apt:
    packages:
      - texlive
      - qttools5-dev-tools
      - libqt5sql5-sqlite
      - texinfo
  homebrew:
    packages:
      - octave
      - qt
      - findutils
      - gcc

matrix:
  include:
    - os: linux
      dist: xenial
      env: 
        - dist="Xenial 16.x"
        - OCTAVE="flatpak run org.octave.Octave"
    - os: osx
      osx_image: xcode11.3

install:
  # Install Octave 4.4, even if it's not the default
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];   then ./dev-tools/install-octave-ubuntu.sh;  fi

script:
  - echo PATH=$PATH
  - $OCTAVE --eval "ver"
  # We only build the docs on Linux because it requires TeX and the macOS TeX install is a monster.
  # We only need the doc build for verifying doc changes anyway; we don't need multi-platform
  # artifacts, or even the new artifacts at all.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make maintainer-clean && make all); fi
  - make dist
  - $OCTAVE --no-gui --eval "pkg install ./target/${OCT_PKG}-${OCT_PKG_VER}.tar.gz"
  - $OCTAVE --no-gui --eval "pkg load $OCT_PKG; pkg unload $OCT_PKG"
  - $OCTAVE --no-gui --eval "__run_tests_and_exit__ $OCT_PKG"
  - $OCTAVE --no-gui --eval "pkg uninstall $OCT_PKG"
