language: c

# Let's build everything for now; comment this out
#branches:
#  only:
#    - master 

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - octave
      - octave-pkg-dev
      - qttools5-dev-tools
      - libqt5sql5-sqlite
      - libjsoncpp-dev
  homebrew:
    packages:
      - octave
      - qt
      - findutils
      - jsoncpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1

script:
  - which octave
  - octave --version
  - make local
  # We only build the docs on Linux because it requires TeX and the macOS TeX install is a monster
  # We only need the doc build for verifying doc changes anyway; we don't need multi-platform
  # artifacts, or even the new artifacts at all.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make maintainer-clean && make all); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then find /usr/include -name json.h; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then find /usr/local/include -name json.h; fi
  - make test
  - make dist
  - octave --eval "pkg install ./target/jsonstuff-0.1.0.tar.gz"
  - octave --eval "pkg load jsonstuff; pkg unload jsonstuff"
  - octave --eval "pkg load jsonstuff; runtests ./inst"
  - octave --eval "pkg uninstall jsonstuff"
  - ./dev-tools/runtests.sh
